### ISSUE TITLE
vanoof.grossartig.io marked as deceptive site by Google Safe Browsing and others

### ISSUE THREAD

**Issue by mariusangelmann** [grossartig/vanmoof-encryption-key-exporter#12]
### Issue Description:
Our website, vanoof.grossartig.io, has been mistakenly marked as a deceptive site by Google Safe Browsing. This misclassification has resulted in a red warning that hinders user access. We respectfully request a thorough reevaluation of our website's classification to rectify this issue.

### Steps to Reproduce:

Access vanoof.grossartig.io.
Observe the deceptive site warning from Google Safe Browsing.

### Expected Behavior:
Users should be able to access vanoof.grossartig.io without encountering any deceptive site warnings.

### Additional Information:

The VanMoof Encryption Key Exporter hosted on vanoof.grossartig.io is a valuable tool, enabling secure encryption key downloads.
We prioritize transparency by open sourcing the project and encouraging code review and self-hosting.
The deceptive site classification adversely affects our ability to serve the community and contribute to reducing e-waste.
Previous appeals to Google have not received a response, prolonging the issue.

We're working on resolving this matter.

**Comment by lmorit** [comment]
Is this because of the easter egg in the project ;)

**Comment by mariusangelmann** [comment]
> Is this because of the easter egg in the project ;)

I wish it was :D

**Comment by Qubica** [comment]
Most likely a typo? https://vanmoof.grossartig.io/

**Comment by Justus-D** [comment]
> Most likely a typo? https://vanmoof.grossartig.io/

No, it's meant to be vanoof. Yes, it's also available as vanmoof.grossartig.io but originally it's a combination of VanMoof and oof.

**Comment by Justus-D** [comment]
Google removed our site from Google Safe browsing! It's now accessible again at [vanoof.grossartig.io](https://vanoof.grossartig.io)!

**Comment by skyfaller** [comment]
Norton Antivirus still reports both [vanoof.grossartig.io](https://vanoof.grossartig.io/) and https://keyexporter.grossartig.io/ as phishing sites. I don't know if this is from the same source as Google Safe browsing, and it's just lagging, or if this is a different authority you need to wrestle with.

**Comment by Bjornftw** [comment]
https://submit.norton.com
