### ISSUE TITLE
Error when Parsing downloaded File

### ISSUE THREAD

**Issue by SoulPictures** [grossartig/vanmoof-encryption-key-exporter#13]
Hey there,

using your hosted service I am able to download a json (which viewed as text) looks fine. Importing it in the Bikey App yields an error that parsing the file failed. At the same time retrieving the data through bikey tells me "no bike found for this account". 

Could there be an incompatibility for the older S3 variants which not yet have the FindMy integration?

My bike refers to be the following according to your json:

- "Edition":"ES-3 2G"
- "modelName":"VM01-200-2G EU"

i am currently away from my bike so sadly I can't edit changes in the VanMoof app which needs a bike to be connected...

Big thanks 
Arne

**Comment by Justus-D** [comment]
As I'm aware, the Bikey app supports our file format or is working on supporting it. Look out for an update of the Bikey app.
For further questions about the Bikey app, please contact their developers. We do not develop the Bikey app.
