### ISSUE TITLE
Application error: a client-side exception has occurred

### ISSUE THREAD

**Issue by jdrees** [grossartig/vanmoof-encryption-key-exporter#2]
When trying to log in (locally an on on vanmoof.grossartig.io), I get the following error message and console logs.
Tried in safari and firefox.

Application error: a client-side exception has occurred (see the browser console for more information).

[Error] Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
	reportError (framework-2c79e2a64abdb08b.js:9:46428)
	(anonymous function) (main-f11614d8aa7ee555.js:1:16887)
	(anonymous function) (framework-2c79e2a64abdb08b.js:9:111467)
	oI (framework-2c79e2a64abdb08b.js:9:111646)
	oS (framework-2c79e2a64abdb08b.js:9:95018)
	oS
	x (framework-2c79e2a64abdb08b.js:33:1375)
	T (framework-2c79e2a64abdb08b.js:33:1905)
[Error] Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
	reportError (framework-2c79e2a64abdb08b.js:9:120834)
	(anonymous function) (main-f11614d8aa7ee555.js:1:16887)
	(anonymous function) (framework-2c79e2a64abdb08b.js:9:111467)
	oI (framework-2c79e2a64abdb08b.js:9:111646)
	oS (framework-2c79e2a64abdb08b.js:9:95018)
	oS
	x (framework-2c79e2a64abdb08b.js:33:1375)
	T (framework-2c79e2a64abdb08b.js:33:1905)
[Error] Failed to load resource: the server responded with a status of 404 () (favicon.ico, line 0)
[Error] Failed to load resource: the server responded with a status of 401 () (getBikes, line 0)
[Error] TypeError: null is not an object (evaluating 'e.key.encryptionKey')
	a6 (framework-2c79e2a64abdb08b.js:9:69820)
	(anonymous function) (framework-2c79e2a64abdb08b.js:9:70332)
	lH (framework-2c79e2a64abdb08b.js:9:51354)
	uY (framework-2c79e2a64abdb08b.js:9:90791)
	e (framework-2c79e2a64abdb08b.js:9:111125)
	(anonymous function) (framework-2c79e2a64abdb08b.js:9:111134)
	oI (framework-2c79e2a64abdb08b.js:9:111646)
	oS (framework-2c79e2a64abdb08b.js:9:95018)
	oS
	x (framework-2c79e2a64abdb08b.js:33:1375)
	T (framework-2c79e2a64abdb08b.js:33:1905)
[Error] TypeError: null is not an object (evaluating 'e.key.encryptionKey')
	K (main-f11614d8aa7ee555.js:1:10101)
	fn (main-f11614d8aa7ee555.js:1:9178)
	componentDidCatch (main-f11614d8aa7ee555.js:1:7668)
	(anonymous function) (framework-2c79e2a64abdb08b.js:9:70440)
	lH (framework-2c79e2a64abdb08b.js:9:51354)
	uY (framework-2c79e2a64abdb08b.js:9:90791)
	e (framework-2c79e2a64abdb08b.js:9:111125)
	(anonymous function) (framework-2c79e2a64abdb08b.js:9:111134)
	oI (framework-2c79e2a64abdb08b.js:9:111646)
	oS (framework-2c79e2a64abdb08b.js:9:95018)
	oS
	x (framework-2c79e2a64abdb08b.js:33:1375)
	T (framework-2c79e2a64abdb08b.js:33:1905)
[Error] A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
	K (main-f11614d8aa7ee555.js:1:10118)
	fn (main-f11614d8aa7ee555.js:1:9178)
	componentDidCatch (main-f11614d8aa7ee555.js:1:7668)
	(anonymous function) (framework-2c79e2a64abdb08b.js:9:70440)
	lH (framework-2c79e2a64abdb08b.js:9:51354)
	uY (framework-2c79e2a64abdb08b.js:9:90791)
	e (framework-2c79e2a64abdb08b.js:9:111125)
	(anonymous function) (framework-2c79e2a64abdb08b.js:9:111134)
	oI (framework-2c79e2a64abdb08b.js:9:111646)
	oS (framework-2c79e2a64abdb08b.js:9:95018)
	oS
	x (framework-2c79e2a64abdb08b.js:33:1375)
	T (framework-2c79e2a64abdb08b.js:33:1905)

**Comment by Justus-D** [comment]
Okay, seems like I have to do more exception handling. I will take a look at this during my next programming session. Thanks for the bug report. Will update you here.

**Comment by ItsFate0815** [comment]
Seems like it has something to do with having an S5 in the Account. We have more than one Vanmoof in the Family, and even if it is a shared S5 the error occurs, but if I remove it everything works fine.

**Comment by jdrees** [comment]
Could be. I also have an s5.

**Comment by Justus-D** [comment]
Is someone able to send me the response from the server? Please censor any sensitive data such as encryption keys or consider sending me an email at "git (at) justus-d.de".

**Comment by hank32601** [comment]
Same for me, I have an A5 and a S3.

**Comment by hank32601** [comment]
If you tell me where to see the server response (I think you mean the vanmoof Server?) I would love to do that.

**Comment by Justus-D** [comment]
Yes, sorry. If you inspect the page, find the request for "GET /api/getBikes" and send me the response. If it contains data that you wish to not post publicly, shoot me an email (git (at) justus-d.de).

**Comment by hank32601** [comment]
> Yes, sorry. If you inspect the page, find the request for "GET /api/getBikes" and send me the response. If it contains data that you wish to not post publicly, shoot me an email (git (at) justus-d.de).

Just sent you an eMail!

**Comment by jdrees** [comment]
VanMoof is bankrupt. :(
https://www.nrc.nl/nieuws/2023/07/12/uitstel-van-betaling-voor-fietsenmerk-vanmoof-a4169615

Let’s hope they don’t shut off everything now.

**Comment by hank32601** [comment]
Yes, I hope too. If it's like the german Insolvenz, there is still some hope....

**Comment by Justus-D** [comment]
The site shouldn't crash anymore. I now check for the missing parameters in the response. If I find the time, I will also implement the full support of the bikes that are causing problems. Keep an eye on this issue and #5 for updates.

**Comment by hank32601** [comment]
Works fine with my S3/A5 Account now! Thanks!

**Comment by Justus-D** [comment]
I will close this issue, because technically the app doesn't crash anymore. Proper support for other bikes is currently tracked at #5
